---
title: "Lab 5: Comparing Ridge, Lasso, and OLS"
author: "Kaori Hirano"
date: "06/07/2023"
format: pdf
---

# Packages

```{r load-packages}
# load packages here
library(ISLR2)
library(leaps) # for best subset selection
library(glmnet) # for ridge, LASSO, and elastic net
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(readr))
library(patchwork) # for plot arrangement
suppressPackageStartupMessages(library(pls)) # for principal component regression and partial least squares
```

# Data  

```{r load-data}
mls22 <- read_csv("data/mls22.csv", show_col_types = FALSE)
d <- dfull |> drop_na()
```


# Data Wrangling

## Q1 

```{r chunk-name-here}
d <- d |>mutate(Nation, usa = if_else(Nation == "USA", 1, 0)) # 0 for non us, 1 for us

# 1 for gk, else 0
gkval <- grepl("GK", d$Pos, fixed = TRUE)
d <- d |> mutate(Pos, gk = if_else(gkval == TRUE, 1, 0))

# 1 for df, else 0
dfval <- grepl("DF", d$Pos, fixed = TRUE)
d <- d |> mutate(Pos, df = if_else(dfval == TRUE, 1, 0))
# head(d) works!

# 1 if mf, 0 if not 
mfval <- grepl("MF", d$Pos, fixed = TRUE)
d <- d |> mutate(Pos, mf = if_else(mfval == TRUE, 1, 0)) 

# 1 for FW and 0 for no
fwval <- grepl("FW", d$Pos, fixed = TRUE)
d <- d |> mutate(Pos, fw = if_else(fwval == TRUE, 1, 0))

d$logs <- log(d$base_salary)
```

# Comparing Predictive Performance

## Q2
```{r q2}
set.seed(16)
dim(d)
mls_cv <- sample(727, (727*.7))
mls_test <- sample(727, (727*.3))
```

## Q3

```{r predict-method}
predict.regsubsets <- function(object, newdata, id, ...) {
  
   if(is.symbol(object$call[[2]])){
     i <- 2
     evals_form <- function(x){
       !rlang::is_formula(eval(x), scoped = TRUE)
     }
     pos_evals_form <- possibly(evals_form, otherwise = FALSE)
     while(pos_evals_form(object$call[[i]])){
      i <- i + 1 
     }
     tt <- eval(object$call[[i]])
   } else {
     tt <- as.formula(object$call[[2]])
   }
   mat <- model.matrix(tt, newdata)
   coefj <- coef(object, id = id)
   xvars <- names(coefj)
   mat[, xvars] %*% coefj
}
```

# Comparing Variable Selection Approaches
